Repository khu-yaong/api-server, pull requests merged in 2024-11, with the labels that each got.

#4 Feat: BaseTimeEntity 생성
  src/main/java/com/khu/yaong/YaongApplication.java
  src/main/java/com/khu/yaong/domain/common/BaseTime.java
Labels: 🌟 Feat

#2 Chore: 프로젝트 패키지 구조 설정
  src/main/java/com/khu/yaong/YaongApplication.java
  src/main/java/com/khu/yaong/domain/common/BaseTime.java
  src/main/java/com/khu/yaong/domain/member/controller/.gitkeep
  src/main/java/com/khu/yaong/domain/member/domain/.gitkeep
  src/main/java/com/khu/yaong/domain/member/dto/.gitkeep
  src/main/java/com/khu/yaong/domain/member/exception/.gitkeep
  src/main/java/com/khu/yaong/domain/member/repository/.gitkeep
  src/main/java/com/khu/yaong/domain/member/service/.gitkeep
  src/main/java/com/khu/yaong/domain/post/controller/.gitkeep
  src/main/java/com/khu/yaong/domain/post/domain/.gitkeep
  src/main/java/com/khu/yaong/domain/post/dto/.gitkeep
  src/main/java/com/khu/yaong/domain/post/exception/.gitkeep
  src/main/java/com/khu/yaong/domain/post/repository/.gitkeep
  src/main/java/com/khu/yaong/domain/post/service/.gitkeep
  src/main/java/com/khu/yaong/global/common/exception/.gitkeep
  src/main/java/com/khu/yaong/global/common/request/.gitkeep
  src/main/java/com/khu/yaong/global/common/response/.gitkeep
  src/main/java/com/khu/yaong/global/config/SecurityConfig.java
  src/main/java/com/khu/yaong/global/config/SwaggerConfig.java
  src/main/java/com/khu/yaong/global/util/.gitkeep
  src/main/java/com/khu/yaong/test/TestController.java
Labels: 🌱 Chore

#33 [FIX] 야구 선수 소속팀 누락 문제 해결
  src/main/java/com/khu/yaong/domain/data/domain/Player.java
  src/main/java/com/khu/yaong/domain/data/dto/PlayerDTO.java
  src/main/java/com/khu/yaong/domain/data/dto/Team.java
Labels: 🛠️ Fix

#41 [MODIFY] S3 서버측에서 업로드하도록 변경
  src/main/java/com/khu/yaong/domain/auth/controller/AuthController.java
  src/main/java/com/khu/yaong/domain/auth/dto/request/MemberRegisterRequestDto.java
  src/main/java/com/khu/yaong/domain/auth/service/AuthService.java
  src/main/java/com/khu/yaong/domain/diary/controller/DiaryController.java
  src/main/java/com/khu/yaong/domain/diary/dto/DiaryRequestDto.java
  src/main/java/com/khu/yaong/domain/diary/service/DiaryService.java
  src/main/java/com/khu/yaong/domain/post/controller/PostController.java
  src/main/java/com/khu/yaong/domain/post/dto/PostReqDTO.java
  src/main/java/com/khu/yaong/domain/post/service/PostService.java
  src/main/java/com/khu/yaong/domain/post/service/PostServiceImpl.java
  src/main/java/com/khu/yaong/global/common/response/s3/S3ErrorCode.java
  src/main/java/com/khu/yaong/global/config/S3Config.java
  src/main/java/com/khu/yaong/global/s3/MultipartMessageConverter.java
  src/main/java/com/khu/yaong/global/s3/S3ImageService.java
Labels: ✏️ Modify

#37 [FEAT] 야구 사전 API 구현
  src/main/java/com/khu/yaong/domain/data/controller/PlayerController.java
  src/main/java/com/khu/yaong/domain/data/controller/WordController.java
  src/main/java/com/khu/yaong/domain/data/domain/Fielder.java
  src/main/java/com/khu/yaong/domain/data/domain/Pitcher.java
  src/main/java/com/khu/yaong/domain/data/domain/Player.java
  src/main/java/com/khu/yaong/domain/data/dto/PlayerDTO.java
  src/main/java/com/khu/yaong/domain/data/dto/PlayerReqDTO.java
  src/main/java/com/khu/yaong/domain/data/dto/PlayerResDTO.java
  src/main/java/com/khu/yaong/domain/data/dto/Team.java
  src/main/java/com/khu/yaong/domain/data/dto/WordResDTO.java
  src/main/java/com/khu/yaong/domain/data/repository/BaseballWordRepository.java
  src/main/java/com/khu/yaong/domain/data/repository/PitcherRepository.java
  src/main/java/com/khu/yaong/domain/data/repository/PlayerRepository.java
  src/main/java/com/khu/yaong/domain/data/repository/querydsl/BaseballWordRepositoryCustom.java
  src/main/java/com/khu/yaong/domain/data/repository/querydsl/BaseballWordRepositoryCustomImpl.java
  src/main/java/com/khu/yaong/domain/data/repository/querydsl/PlayerRepositoryCustom.java
  src/main/java/com/khu/yaong/domain/data/repository/querydsl/PlayerRepositoryCustomImpl.java
  src/main/java/com/khu/yaong/domain/data/service/PlayerRedisService.java
  src/main/java/com/khu/yaong/domain/data/service/PlayerService.java
  src/main/java/com/khu/yaong/domain/data/service/PlayerServiceImpl.java
  src/main/java/com/khu/yaong/domain/data/service/WordService.java
  src/main/java/com/khu/yaong/domain/data/service/WordServiceImpl.java
  src/main/java/com/khu/yaong/domain/member/domain/Team.java
  src/main/java/com/khu/yaong/global/common/response/data/DataErrorCode.java
  src/main/java/com/khu/yaong/global/common/response/data/DataSuccessCode.java
  src/main/java/com/khu/yaong/global/config/RedisConfig.java
  src/main/java/com/khu/yaong/global/loader/PlayerDataLoader.java
Labels: 🌟 Feat

#43 [fix] 게시글 좋아요 isLiked 항목 추가
  src/main/java/com/khu/yaong/domain/post/dto/PostResDTO.java
  src/main/java/com/khu/yaong/domain/post/service/PostServiceImpl.java
Labels: 🛠️ Fix

#44 [FIX] 게시글 isLiked 항목 추가
  src/main/java/com/khu/yaong/domain/post/dto/PostResDTO.java
  src/main/java/com/khu/yaong/domain/post/service/PostServiceImpl.java
Labels: 🛠️ Fix
